spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb-dev:IhKboNh1Y5PMq4zL@cluster0.vhy3t.mongodb.net/sample_airbnb?retryWrites=true&w=majority
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
logging:
 level:
   org.springframework.data.mongodb.repository: debug
   org.springframework.cloud.sleuth: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'