spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
logging:
 level:
   org.springframework.data.mongodb.repository: debug
   org.springframework.cloud.sleuth: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'